# Generated by Django 3.2.6 on 2021-09-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('comentario', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimento.orgao')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimento.municipe')),
            ],
        ),
    ]
