# Generated by Django 3.2.6 on 2021-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgao',
            name='id',
        ),
        migrations.AddField(
            model_name='orgao',
            name='orgao_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
