# Generated by Django 3.2.6 on 2021-10-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0002_alter_requisicao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='comentario',
            field=models.CharField(max_length=3000),
        ),
    ]
