# Generated by Django 3.2.6 on 2021-11-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0003_alter_requisicao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
